fragment SiteSettingsParts on SiteSettings {
  __typename
  name
  description
  descriptionEn
  status
  bannerImage
  authorBio
  authorBioEn
  githubUrl
  email
}

fragment CategoryParts on Category {
  __typename
  name
  nameEn
  icon
  subcategories {
    __typename
    name
    nameEn
  }
}

fragment BlogParts on Blog {
  __typename
  title
  titleEn
  description
  descriptionEn
  date
  tags
  category
  coverImage
  draft
  body
}
